import Head from 'next/head'
import NavBar from '../components/NavBar'

import c from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={c.root}>
      <Head>
        <title>CRBT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={c.header}>
        <div className={c.banner} />
        <NavBar />
        <h1>The Discord companion made for you.</h1>
        <p>
          Quit the hassle and ditch all of your different bots. <br />
          CRBT is easy, powerful and efficient.
        </p>
        <a href='/invite' className={c.inviteButton}>Invite</a>
      </header>

      <section className={c.section1}>
        <h1>Why CRBT?</h1>
      </section>
    </div>
  )
}
